SaveDoc/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Dominio.Contratos;
using Dominio.EntidadesDto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SaveDoc.Controllers
{
    [Authorize]
    public class AreaController : Controller
    {
        private readonly IAreaDominio areaDom;

        public AreaController(IAreaDominio areaDom)
        {
            this.areaDom = areaDom;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> _ListaAreaCuadro()
        {
            
            try
            {
                var listaArea = await areaDom.ObtenerListaArea();
                return PartialView(listaArea);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message);
            }
        }

        public async Task<IActionResult> _FormularioArea([FromBody]int AreaId)
        {
            try
            {
                var area = await areaDom.ObtenerAreaById(AreaId);
                return PartialView(area);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message);
            }
        }

        public async Task<IActionResult> GuardarArea(AreaDto area)
        {
            Thread.Sleep(1500);
            var mensaje = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    var retorno = (area.AreaId > 0) ? await areaDom.ActualizarArea(area) : await areaDom.AgregarArea(area);
                    if (retorno)
                    {
                        Response.StatusCode = (int)HttpStatusCode.OK;
                        mensaje = "Se registró el área correctamente!!";
                    }
                    else
                    {
                        Response.StatusCode = (int)HttpStatusCode.BadRequest;
                        mensaje = "Se generó un error al registrar el área!!";
                    }
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    mensaje = "Favor introducir correctamente los datos!";
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                mensaje = ex.Message;
            }
            return Json(mensaje);
        }

        public async Task<IActionResult> _EliminarArea([FromBody] int AreaId)
        {
            var mensaje = string.Empty;
            try
            {
                var retorno = await areaDom.EliminarArea(AreaId);
                if (retorno)
                {
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    mensaje = "Se eliminó el área correctamente!!";
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    mensaje = "Se generó un error al eliminar el área!!";
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                mensaje = ex.Message;
            }
            return Json(mensaje);
        }

    }
}

SaveDoc/Controllers/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Dominio.Contratos;
using Dominio.EntidadesDto;
using InfraEstructura.Transversal;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SaveDoc.Controllers
{
    [Authorize]
    public class DocumentoController : Controller
    {
        private readonly IAreaDominio areaDom;
        private readonly IDocumentoDominio documentoDom;

        int _RegistrosPorPagina = 4;
        Paginador<DocumentoDto> _PaginadorDocumentos;

        public DocumentoController(IAreaDominio area, IDocumentoDominio documento)
        {
            this.areaDom = area;
            this.documentoDom = documento;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var listaDoc = await documentoDom.ObtenerTodosDocumentos();
            _PaginadorDocumentos = PaginacionCards(1, listaDoc.Count, listaDoc);
            ViewBag.documentos = _PaginadorDocumentos;

            var areas = await areaDom.ObtenerListaArea();
            ViewBag.Area = areas;


            return View();
        }

        public async Task<IActionResult> _BuscarDocumentoPorArea([FromBody] int areaId)
        {
            try
            {
                var listaDoc = (areaId == 99) ? await documentoDom.ObtenerTodosDocumentos() : await documentoDom.ObtenerDocumentoArea(areaId);
                if (listaDoc.Count > 0)
                {
                    _PaginadorDocumentos = PaginacionCards(1, listaDoc.Count, listaDoc);
                    ViewBag.documentos = _PaginadorDocumentos;

                    var areas = await areaDom.ObtenerListaArea();
                    ViewBag.Area = areas;
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return PartialView("_Card", _PaginadorDocumentos);
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    var mensaje = "No existen documentos relacionados a esta área.";
                    return Json(mensaje);
                }

            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = ex.Message });
            }
        }

        public async Task<IActionResult> _BuscarDocumentoPorNombre([FromBody] string doc)
        {
            try
            {
                var documento = await documentoDom.ObtenerDocumentoPorNombre(doc);
                if (documento.Count > 0)
                {
                    _PaginadorDocumentos = PaginacionCards(1, documento.Count, documento);
                    ViewBag.documentos = _PaginadorDocumentos;
                    var areas = await areaDom.ObtenerListaArea();
                    ViewBag.Area = areas;
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    return PartialView("_Card", _PaginadorDocumentos);
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    var mensaje = "No existen documentos relacionados a esta área.";
                    return Json(mensaje);
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = ex.Message });
            }
        }

        public IActionResult _NuevoDocumento([FromBody] int docId)
        {
            try
            {
                var documento = documentoDom.ObtenerDocumentoPorId(docId).Result;
                var areas = areaDom.ObtenerListaArea().Result;
                List<SelectListItem> lst = new List<SelectListItem>();
                foreach (var item in areas)
                {
                    lst.Add(new SelectListItem() { Text = item.Nombre, Value = item.AreaId.ToString(), Selected = (documento != null) ? (item.AreaId.Equals(documento.AreaId)) : false });
                }
                ViewBag.Area = lst;
                return PartialView(documento);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { message = ex.Message });
            }
        }

        [Authorize]
        public async Task<IActionResult> _DescargarDocumento(int id)
        {
            var documento = await documentoDom.ObtenerDocumentoByte(id);
            return File(documento.Doc, documento.Extension);
        }

        [RequestFormLimits(MultipartBodyLengthLimit = 209715200)]
        [RequestSizeLimit(209715200)]
        public IActionResult SaveDoc(DocumentoDto doc)
        {
            Thread.Sleep(2000);
            var mensaje = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    var retorno = (doc.DocumentoId > 0) ? documentoDom.ActualizarDocumento(doc) : documentoDom.AgregarDocumento(doc);
                    if (retorno.Result)
                    {
                        Response.StatusCode = (int)HttpStatusCode.OK;
                        mensaje = "Se registró el documento correctamente!!";
                    }
                    else
                    {
                        Response.StatusCode = (int)HttpStatusCode.BadRequest;
                        mensaje = "Se generó un error al registrar el documento!!";
                    }
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    mensaje = "Favor introducir correctamente los datos!";
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                mensaje = ex.Message;
            }
            return Json(mensaje);
        }

        public async Task<IActionResult> _ListaDocCards()
        {
            try
            {
                var listaDoc = await documentoDom.ObtenerTodosDocumentos();
                return PartialView(listaDoc);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message);
            }
        }

        public async Task<IActionResult> _EliminarDocumento([FromBody] int docId)
        {
            var mensaje = string.Empty;
            try
            {
                var retorno = await documentoDom.EliminarDocumento(docId, out mensaje);
                if (retorno)
                {
                    Response.StatusCode = (int)HttpStatusCode.OK;
                    //mensaje = "Se eliminó el documento correctamente!!";
                }
                else
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    //mensaje = "Se generó un error al eliminar el área!!!";
                }
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                mensaje = ex.Message;
            }
            return Json(mensaje);
        }


        private Paginador<DocumentoDto> PaginacionCards(int pagina, int _TotalRegistros, List<DocumentoDto> Listado)
        {
            var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
            pagina = pagina == 0 ? 1 :
                     pagina > _TotalPaginas ? _TotalPaginas :
                     pagina;
           

            var ListFiltrada = Listado.OrderBy(x => x.AreaId)
                 .Skip((pagina - 1) * _RegistrosPorPagina)
                 .Take(_RegistrosPorPagina)
                 .ToList();



            _PaginadorDocumentos = new Paginador<DocumentoDto>()
            {
                RegistrosPorPagina = _RegistrosPorPagina,
                TotalRegistros = _TotalRegistros,
                TotalPaginas = _TotalPaginas,
                PaginaActual = pagina,
                Resultado = ListFiltrada
            };

            return _PaginadorDocumentos;
        }

        public async Task<IActionResult> _Card(int pagina = 1, int filtro = 0)
        {
            var Listadoc = (filtro == 0 || filtro == 99) ? await documentoDom.ObtenerTodosDocumentos() : await documentoDom.ObtenerDocumentoArea(filtro);

            _PaginadorDocumentos = PaginacionCards(pagina, Listadoc.Count, Listadoc);

            return PartialView(_PaginadorDocumentos);
        }
    }
}

SaveDoc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SaveDoc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SaveDoc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - SaveDoc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SaveDoc/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    @*<li class="header">***************************************</li>*@
    <!-- Optionally, you can add icons to the links -->
    <li><a href="@Url.Action("Index", "Documento")"><i class="fa fa-archive"></i> <span>Documentos</span></a></li>
    <li><a href="@Url.Action("Index", "Area")"><i class="fa fa-map"></i> <span>Areas</span></a></li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-users"></i> <span>Usuarios</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li>
                <a href="@Url.Action("AdministrarCuentas","Account")">
                    <i class="fa fa-user-plus"></i>
                    Administrar Cuentas
                </a>
            </li>

            <li>
                <a href="@Url.Action("AdministrarRoles","Account")">
                    <i class="fa fa-gears"></i>
                    Administrar Roles
                </a>
            </li>
        </ul>
        
    </li>
</ul>